name: 🙋‍♂️ [FileSentinel] - Support & Feedback
description: Get help with FileSentinel, report bugs, or request features.
title: '🙋‍♂️ Support & Feedback: FileSentinel'
labels: ['support', 'feedback', 'question']
assignees:
  - jaywcjlove
body:
  - type: markdown
    attributes:
      value: |
        <img align="right" height="86" alt="FileSentinel" src="https://github.com/user-attachments/assets/28bce2cc-290e-45bf-9068-585ff6ecafe9"> Please provide as much detail as possible about your support request or feedback.
        
        FileSentinel is a tool for monitoring text file changes, saving the last line of content, and conveniently querying terminal command history. It can monitor files such as .zsh_history or .bash_history, automatically saving shell history records to help you quickly search recent terminal commands and avoid forgetting important ones. The App supports full-text search and command pinning to improve your work efficiency.

        ### Contact Information

        If you encounter any issues or need support while using our app, please feel free to contact us through the following methods:

        - **Email Support**: [kennyiseeyou@gmail.com](mailto:kennyiseeyou@gmail.com)
        - **Social Media**: [Twitter](https://twitter.com/jaywcjlove)

        We will respond to your message as soon as possible. Thank you for your support of our app!

  - type: textarea
    attributes:
      label: 🙋‍♂️ How can we help you?
      description: Describe the issue you're facing or the feature you'd like to request.
      placeholder: For example, I'm experiencing an issue with...
    validations:
      required: true

  - type: dropdown
    id: os_version
    attributes:
      label: "💻 Desktop"
      description: Your operating system and version.
      options:
        - macOS 15.0 (Sequoia)
        - macOS 14.0 (Sonoma)
      default: 0
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        **How can I send you a crash report for one of your apps?**

        - macOS Open Finder
        - Select Go to **Folder…** from the Go menu <kbd>⇧</kbd> + <kbd>⌘</kbd> + <kbd>G</kbd>
        - Enter: **~/Library/Logs/DiagnosticReports**
        - In the resulting list, select all files that starts with the app name, ZIP them, and send me
        - Attach the file to this issue

  - type: textarea
    attributes:
      label: ℹ️ Additional context
      description: Add any additional information that could be helpful.
      placeholder: ex. Screenshots, steps to reproduce, etc.
    validations:
      required: false